name: Search Ingest Trigger

on: 
  repository_dispatch:
    types:
      - resource-published
      - resource-unpublished

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "Status: ${{ github.event.client_payload.status }}"
        echo "Path: ${{ github.event.client_payload.path }}"
  search-ingest:
    if: (github.event.client_payload.status == 200 || github.event.client_payload.status == 204) && endsWith(github.event.client_payload.path, '.md')
    runs-on: ubuntu-latest
    steps:
    # - name: Remove .md extension
    #   id: removeMd
    #   uses: frabert/replace-string-action@v2
    #   with:
    #     pattern: '\.md$'
    #     string: ${{ github.event.client_payload.path }}
    #     replace-with: ''
    - name: Build search endpoint
      id: searchEndpoint
      uses: frabert/replace-string-action@v2
      with:
        pattern: '{{path}}'
        string: ${{ github.event.client_payload.status == 200 && vars.SEARCH_API_INGEST_PATTERN || vars.SEARCH_API_DELETE_PATTERN }}
        replace-with: ${{ steps.removeMd.outputs.replaced }}
    - name: Trigger search API
      uses: fjogeleit/http-request-action@v1
      with:
        url: ${{ steps.searchEndpoint.outputs.result }}
        method: 'POST'
        timeout: 20000
