name: Slack Publish Notifications

on: 
  repository_dispatch:
    types:
      - resource-published

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "Status: ${{ github.event.client_payload.status }}"
        echo "Path: ${{ github.event.client_payload.path }}"
  slack-notification:
    if: github.event.client_payload.status == 200
    runs-on: ubuntu-latest
    steps:
    - name: Remove .md extension
      id: removeMd
      uses: frabert/replace-string-action@v2
      with:
        pattern: '\.md$'
        string: ${{ github.event.client_payload.path }}
        replace-with: ''
    - name: Notify Slack (JSON)
      if: ${{ endsWith(github.event.client_payload.path, '.json') }}
      uses: slackapi/slack-github-action@v1.23.0
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_NOTIFICATION_WEBHOOK }}
      with:
        # For posting a rich message using Block Kit
        payload: |
          {
            "text": "Just published: `${{ github.event.client_payload.path }}`"
          }
    - name: Notify Slack (Markdown)
      if: ${{ endsWith(github.event.client_payload.path, '.md') }}
      uses: slackapi/slack-github-action@v1.23.0
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_NOTIFICATION_WEBHOOK }}
      with:
        # For posting a rich message using Block Kit
        payload: |
          {
            "text": "Just published: https://www.netcentri.biz${{ steps.removeMd.outputs.replaced }}"
          }