name: Slack Release Notification

on:
  push:
    branches:
      - main

jobs:
  checkType:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Find last merge
      run: |
        echo "current_commit=$(git log --pretty='%H' -1)" >> $GITHUB_ENV
        echo "last_merge=$(git log --pretty='%H' --merges -1 --first-parent)" >> $GITHUB_ENV
    outputs:
      last_merge: ${{ env.last_merge }}
      current_commit: ${{ env.current_commit }}
  directCommit:
    runs-on: ubuntu-latest
    needs: checkType
    if: ${{ needs.checkType.outputs.last_merge }} != ${{ needs.checkType.outputs.current_commit }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: get commit message
      run: echo "commit_message=$(git log --pretty='%s' -1)" >> $GITHUB_ENV
    - name: debug
      run: |
        echo ${{ env.commit_message }}
    # the following action is based on a workflow created by Andreas Haller, contact for permissions, the workflow file to import can be found under tools/slack
    - name: Notify Slack
      uses: slackapi/slack-github-action@v1.23.0
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_NOTIFICATION_WEBHOOK_TEST }}
      with:
        payload: |
          {
            "text": "Direct commit to main: |
               ${{ env.commit_message }}"
          }
  mergeCommit:
    runs-on: ubuntu-latest
    needs: checkType
    if: ${{ needs.checkType.outputs.last_merge }} == ${{ needs.checkType.outputs.current_commit }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: debug
      run: |
        echo ${{ needs.checkType.outputs.last_merge }}
        echo ${{ needs.checkType.outputs.current_commit }}
    - name: get commit messages
      run: |
        previous_merge=$(git log --pretty="%h" -1 --merges --skip=1 --first-parent)
        second_parent=$(git log --pretty="%h" -1 ${{ needs.checkType.outputs.last_merge }}^2)
        echo "commit_messages=$(git log --pretty='%h (%an, %ae): %s' --no-merges $previous_merge..$second_parent)" >> $GITHUB_ENV
    - name: debug
      run: |
        echo ${{ env.commit_messages }}
    # the following action is based on a workflow created by Andreas Haller, contact for permissions, the workflow file to import can be found under tools/slack
    # - name: Notify Slack
    #   uses: slackapi/slack-github-action@v1.23.0
    #   env:
    #     SLACK_WEBHOOK_URL: ${{ secrets.SLACK_NOTIFICATION_WEBHOOK }}
    #   with:
    #     payload: |
    #       {
    #         "text": "New code version released."
    #       }
  test0:
    runs-on: ubuntu-latest
    if: false
    steps:
    - name: test step
      run: echo "running"
  test1:
    runs-on: ubuntu-latest
    if: true
    steps:
    - name: test step
      run: echo "running"
